name: psychopy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.18
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - opencv
  - psychopy=2022.2.5
  - imageio
  - pyopengl
  - pyglet
  - wxpython
  - configobj
  - pyyaml
  - pillow
  - openpyxl
  - requests
  - pyserial
  - psutil
  - pyqt
  - pip:
      - pyglet==1.5.27
      - psychtoolbox
      - pygame==2.5.2
      - speechrecognition==3.10.0
      - ffpyplayer==4.5.1
      - python-vlc==3.0.18122
      - egi-pynetstation==1.0.0
      - questplus==2019.3
      - javascripthon
      - pipreqs
      - google-api-core
      - google-auth
      - google-cloud
      - google-cloud-speech
      - googleapis-common-protos
